const firebaseConfig={apiKey:"AIzaSyDADKrFkmuLTYfpH9PGd2xY6j_UJT0CVFg",authDomain:"moneyyy-bea87.firebaseapp.com",projectId:"moneyyy-bea87",storageBucket:"moneyyy-bea87.firebasestorage.app",messagingSenderId:"993162981365",appId:"1:993162981365:web:706344878dce215523fabc",measurementId:"G-TK1JTGWDZR"};
const $=id=>document.getElementById(id);const money=new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0});
const state={route:"home",entryKind:"expense",accounts:[],transactions:[],settlements:[],legacyWallets:[{id:"A",label:"伊🍊寶",balance:0},{id:"B",label:"阿帥",balance:0},{id:"Coin",label:"零錢包",balance:0}],legacyTransactions:[],goals:[],members:[],budgets:[],familyName:localStorage.getItem("moneycanFamilyName")||"我們的生活",private:localStorage.getItem("moneycanPrivate")==="1",dark:localStorage.getItem("moneycanDark")==="1",cloud:false,installPrompt:null};
const expenseCategories=["餐飲","交通","購物","娛樂","帳單","居家","醫療","學習","禮物","其他"],incomeCategories=["薪水","獎金","投資","退款","其他"];
let db=null;
try{if(window.firebase){firebase.initializeApp(firebaseConfig);db=firebase.firestore()}}catch(error){console.warn("Firebase 初始化失敗",error)}

function escapeHtml(value){const node=document.createElement("div");node.textContent=String(value??"");return node.innerHTML}
function toDate(value){if(value?.toDate)return value.toDate();if(Number.isFinite(Number(value?.seconds)))return new Date(Number(value.seconds)*1000+Math.floor(Number(value.nanoseconds||0)/1e6));const date=new Date(value||0);return Number.isNaN(date.getTime())?new Date(0):date}
function formatDate(value){return toDate(value).toLocaleDateString("zh-TW",{month:"numeric",day:"numeric"})}
function notify(message,error=false){const toast=$("toast");toast.textContent=message;toast.className=`toast show${error?" error":""}`;clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.className="toast",2600)}
function iconFor(category){return({餐飲:"食",交通:"行",購物:"購",娛樂:"樂",帳單:"帳",居家:"家",醫療:"醫",薪水:"薪",獎金:"獎",投資:"投",退款:"退"})[category]||"記"}
function emptyState(icon,title,text){return `<div class="empty-state"><span>${icon}</span><strong>${title}</strong><small>${text}</small></div>`}
function accountTypeLabel(type){return({cash:"現金",bank:"銀行帳戶",ewallet:"電子支付",card:"信用卡"})[type]||"帳戶"}
function normalizeAccounts(accounts){return accounts.map((account,index)=>({...account,ownerId:account.ownerId||(account.name?.includes("共同")?"shared":index===2?"partner":"me")}))}
function accountOwnerLabel(account){return account?.ownerId==="shared"?"共同帳戶":memberById(account?.ownerId)?.name||"個人帳戶"}
function accountById(id){return state.accounts.find(account=>account.id===id)}
function transactionKind(item){if(item.kind)return item.kind;return item.action==="deposit"?"income":"expense"}

function localLedger(){try{return JSON.parse(localStorage.getItem("moneyCanLedgerV2"))||{}}catch{return {}}}
function saveLocalLedger(){localStorage.setItem("moneyCanLedgerV2",JSON.stringify({accounts:state.accounts,transactions:state.transactions,settlements:state.settlements,members:state.members,budgets:state.budgets}))}
function localLegacy(){try{return JSON.parse(localStorage.getItem("familyMoneyBookV2"))||{}}catch{return {}}}
function saveLocalGoals(){const data=localLegacy();data.goals=state.goals;localStorage.setItem("familyMoneyBookV2",JSON.stringify(data))}

async function loadLedger(){
  const defaults=[{id:"cash",name:"我的現金",type:"cash",ownerId:"me",balance:0},{id:"bank",name:"共同生活帳戶",type:"bank",ownerId:"shared",balance:0},{id:"pay",name:"伴侶電子支付",type:"ewallet",ownerId:"partner",balance:0}];
  const local=localLedger();state.members=[{id:"me",name:"我"},{id:"partner",name:"伴侶"}];
  if(db){try{const [accounts,transactions,household,settlementSnap]=await Promise.all([db.collection("ledgerAccounts").get(),db.collection("ledgerTransactions").orderBy("time","desc").get(),db.collection("settings").doc("household").get(),db.collection("ledgerSettlements").orderBy("time","desc").get().catch(error=>{console.warn("雲端結算紀錄不可用，暫用本機紀錄",error);return null})]);state.accounts=normalizeAccounts(accounts.empty?defaults:accounts.docs.map(doc=>({id:doc.id,...doc.data()})));state.transactions=transactions.docs.map(doc=>({id:doc.id,...doc.data()}));state.settlements=settlementSnap?settlementSnap.docs.map(doc=>({id:doc.id,...doc.data()})):Array.isArray(local.settlements)?local.settlements:[];if(household.exists){if(Array.isArray(household.data().members)&&household.data().members.length)state.members=household.data().members;if(Array.isArray(household.data().budgets))state.budgets=household.data().budgets}state.cloud=true;return}catch(error){console.warn("新記帳雲端資料不可用，改用本機",error)}}
  state.accounts=normalizeAccounts(Array.isArray(local.accounts)&&local.accounts.length?local.accounts:defaults);state.transactions=Array.isArray(local.transactions)?local.transactions:[];state.settlements=Array.isArray(local.settlements)?local.settlements:[];state.members=Array.isArray(local.members)&&local.members.length?local.members:[{id:"me",name:"我"},{id:"partner",name:"伴侶"}];state.budgets=Array.isArray(local.budgets)?local.budgets:[]
}
async function loadLegacy(){
  if(db){try{const [walletSnap,transactionSnap,goalDoc]=await Promise.all([db.collection("wallets").get(),db.collection("transactions").orderBy("time","desc").get(),db.collection("settings").doc("savingsGoals").get()]);walletSnap.forEach(doc=>{const wallet=state.legacyWallets.find(item=>item.id===doc.id);if(wallet)wallet.balance=Number(doc.data().balance)||0});state.legacyTransactions=transactionSnap.docs.map(doc=>({id:doc.id,...doc.data()}));if(goalDoc.exists&&Array.isArray(goalDoc.data().items))state.goals=goalDoc.data().items;state.cloud=true;return}catch(error){console.warn("舊存錢資料雲端讀取失敗，改用本機",error)}}
  const local=localLegacy();state.legacyWallets.forEach(wallet=>wallet.balance=Number(local.wallets?.[wallet.id])||0);state.legacyTransactions=Array.isArray(local.transactions)?local.transactions:[];state.goals=Array.isArray(local.goals)?local.goals:[]
}

function setRoute(route){state.route=route;document.querySelectorAll(".page").forEach(page=>page.classList.toggle("active",page.dataset.page===route));document.querySelectorAll("[data-route]").forEach(button=>button.classList.toggle("active",button.dataset.route===route));const titles={home:"早安，今天也一起記帳",transactions:"每一筆，都算數",savings:"一起存下想要的生活",settings:"把帳本調整成你們的樣子"};$("pageTitle").textContent=titles[route]||titles.home;location.hash=route==="home"?"":route;window.scrollTo({top:0,behavior:"smooth"});render()}
function monthTransactions(){const now=new Date();return state.transactions.filter(item=>{const date=toDate(item.time);return date.getFullYear()===now.getFullYear()&&date.getMonth()===now.getMonth()})}
function stats(){const month=monthTransactions(),income=month.filter(item=>transactionKind(item)==="income").reduce((sum,item)=>sum+Number(item.amount||0),0),expense=month.filter(item=>transactionKind(item)==="expense").reduce((sum,item)=>sum+Number(item.amount||0),0);return{income,expense,net:income-expense,rate:income>0?Math.max(0,Math.round((income-expense)/income*100)):0}}
function memberById(id){return state.members.find(member=>member.id===id)}
function integerShares(item){const members=state.members,total=Math.max(0,Math.round(Number(item.amount)||0));if(!members.length)return{};const allocations=Array.isArray(item.allocations)?item.allocations:[],custom=["percent","amount"].includes(item.split);let weights=members.map(member=>custom?Math.max(0,Number(allocations.find(entry=>entry.memberId===member.id)?.value)||0):1),weightTotal=weights.reduce((sum,value)=>sum+value,0);if(weightTotal<=0){weights=members.map(()=>1);weightTotal=members.length}const exact=weights.map(value=>total*value/weightTotal),shares=exact.map(Math.floor);let remaining=total-shares.reduce((sum,value)=>sum+value,0),cursor=0;const order=exact.map((value,index)=>({index,fraction:value-Math.floor(value)})).sort((a,b)=>b.fraction-a.fraction||a.index-b.index);while(remaining>0&&order.length){shares[order[cursor%order.length].index]++;remaining--;cursor++}return Object.fromEntries(members.map((member,index)=>[member.id,shares[index]]))}
function settlement(){const net=Object.fromEntries(state.members.map(member=>[member.id,0]));state.transactions.filter(item=>transactionKind(item)==="expense"&&accountById(item.accountId)?.ownerId!=="shared"&&item.split!=="none").forEach(item=>{const payer=item.paidBy||accountById(item.accountId)?.ownerId||state.members[0]?.id,amount=Math.max(0,Math.round(Number(item.amount)||0)),shares=integerShares(item);state.members.forEach(member=>net[member.id]-=shares[member.id]||0);if(net[payer]!==undefined)net[payer]+=amount});state.settlements.forEach(item=>{const amount=Math.max(0,Math.round(Number(item.amount)||0));if(net[item.fromMemberId]!==undefined)net[item.fromMemberId]+=amount;if(net[item.toMemberId]!==undefined)net[item.toMemberId]-=amount});const creditors=state.members.map(member=>({id:member.id,value:net[member.id]||0})).filter(item=>item.value>0).sort((a,b)=>b.value-a.value),debtors=state.members.map(member=>({id:member.id,value:-(net[member.id]||0)})).filter(item=>item.value>0).sort((a,b)=>b.value-a.value),items=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const amount=Math.min(debtors[i].value,creditors[j].value);items.push({from:debtors[i].id,to:creditors[j].id,amount});debtors[i].value-=amount;creditors[j].value-=amount;if(debtors[i].value<1)i++;if(creditors[j].value<1)j++}return items}
function transactionRow(item,{legacy=false}={}){const kind=legacy?(item.action==="deposit"?"income":"expense"):transactionKind(item),account=legacy?state.legacyWallets.find(wallet=>wallet.id===(item.walletId||item.who)):accountById(item.accountId||item.walletId),label=legacy?(kind==="income"?"存入":"提領"):(item.note||item.category||"未分類"),payer=account?.ownerId==="shared"?"共同帳戶":memberById(item.paidBy||account?.ownerId)?.name||item.member||"個人",scope=account?.ownerId==="shared"?"共同帳戶付款":item.split&&item.split!=="none"?`${payer}付款 · 已分攤`:`${payer}自行負擔`,sub=legacy?`${account?.label||item.who||"存錢筒"} · ${item.category||"未分類"}`:`${account?.name||"未命名帳戶"} · ${scope}`,edit=legacy?"":`<button class="transaction-edit-button" data-transaction-edit="${item.id}" type="button">編輯</button>`;return `<article class="transaction-row"><div class="transaction-icon ${kind}">${iconFor(item.category)}</div><div class="transaction-main"><strong>${escapeHtml(label)}</strong><small>${escapeHtml(sub)} · ${formatDate(item.time)}</small></div><div class="transaction-amount ${kind}"><strong>${kind==="income"?"+":"−"}${money.format(Number(item.amount)||0)}</strong><small>${kind==="income"?"收入":"支出"}</small>${edit}</div></article>`}

function renderHome(){const summary=stats(),total=state.accounts.reduce((sum,item)=>sum+Number(item.balance||0),0);$("totalBalance").textContent=money.format(total);$("monthIncome").textContent=money.format(summary.income);$("monthExpense").textContent=money.format(summary.expense);$("savingRate").textContent=`${summary.rate}%`;$("monthNetText").textContent=`本月結餘 ${money.format(summary.net)}`;$("accountCountText").textContent=`${state.accounts.length} 個帳戶`;$("recentTransactions").innerHTML=state.transactions.length?state.transactions.slice(0,6).map(item=>transactionRow(item)).join(""):emptyState("＋","還沒有記帳紀錄","按下「記一筆」開始記錄你們的生活");$("accountPreview").innerHTML=state.accounts.slice(0,4).map((item,index)=>`<div class="account-row"><div><span class="account-dot" style="background:${["#5b78f6","#69d8d0","#f5a65b","#e75f66"][index%4]}"></span><div><strong>${escapeHtml(item.name)}</strong><small>${accountTypeLabel(item.type)} · ${escapeHtml(accountOwnerLabel(item))}</small></div></div><strong class="private-value">${money.format(Number(item.balance)||0)}</strong></div>`).join("");renderGoalPreview();renderSettlement()}
function settlementHistoryRow(item){return `<div class="settlement-history-row"><span>${escapeHtml(memberById(item.fromMemberId)?.name||"成員")} → ${escapeHtml(memberById(item.toMemberId)?.name||"成員")} · ${formatDate(item.time)}</span><strong class="private-value">${money.format(Number(item.amount)||0)}</strong><button class="settlement-undo" data-settlement-undo="${escapeHtml(item.id)}" type="button">撤銷</button></div>`}
function renderSettlement(){const items=settlement();$("settlementBadge").textContent=items.length?"待結算":"已平衡";$("settlementBadge").style.color=items.length?"var(--orange)":"var(--green)";$("settlementPreview").innerHTML=items.length?items.map(item=>`<div class="settlement-line"><span>${escapeHtml(memberById(item.from)?.name||"成員")} 應付給 ${escapeHtml(memberById(item.to)?.name||"成員")}</span><strong class="private-value">${money.format(item.amount)}</strong><button class="settlement-pay-button" data-settlement-pay data-from="${escapeHtml(item.from)}" data-to="${escapeHtml(item.to)}" data-amount="${item.amount}" type="button">標記已付</button></div>`).join(""):emptyState("✓","目前沒有代墊差額","共同支出已經平衡");if(!state.settlements.length){$("settlementHistory").innerHTML="";return}const recent=state.settlements.slice(0,3),older=state.settlements.slice(3);$("settlementHistory").innerHTML=`<span class="settlement-history-title">結算紀錄</span>${recent.map(settlementHistoryRow).join("")}${older.length?`<details class="settlement-older"><summary>查看更早 ${older.length} 筆</summary>${older.map(settlementHistoryRow).join("")}</details>`:""}`}
function renderTransactions(){const query=$("transactionSearch").value.trim().toLowerCase(),type=$("transactionType").value,account=$("transactionAccount").value,month=$("transactionMonth").value;const items=state.transactions.filter(item=>{const kind=transactionKind(item),date=toDate(item.time),monthKey=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`,text=`${item.note||""} ${item.category||""} ${item.member||""}`.toLowerCase();return(!query||text.includes(query))&&(type==="all"||kind===type)&&(account==="all"||(item.accountId||item.walletId)===account)&&(!month||monthKey===month)});$("transactionList").innerHTML=items.length?items.map(item=>transactionRow(item)).join(""):emptyState("⌕","找不到符合的明細","調整篩選條件或新增一筆記帳");renderInsights()}
function categoryTotals(){const totals={};monthTransactions().filter(item=>transactionKind(item)==="expense").forEach(item=>totals[item.category||"其他"]=(totals[item.category||"其他"]||0)+Number(item.amount||0));return Object.entries(totals).sort((a,b)=>b[1]-a[1])}
function renderInsights(){const totals=categoryTotals(),top=totals[0],expense=stats().expense,average=expense/Math.max(1,new Date().getDate()),budgetTotal=state.budgets.reduce((sum,item)=>sum+Number(item.amount||0),0),usage=budgetTotal?Math.round(expense/budgetTotal*100):0;$("topCategory").textContent=top?.[0]||"尚無資料";$("topCategoryAmount").textContent=top?`${money.format(top[1])}，占本月 ${expense?Math.round(top[1]/expense*100):0}%`:"開始記帳後顯示";$("dailyAverage").textContent=money.format(Math.round(average));$("budgetStatus").textContent=budgetTotal?`${usage}%`:"尚未設定";$("budgetStatusText").textContent=budgetTotal?(usage>100?"已超出本月總預算":usage>=80?"接近本月預算上限":"目前控制得很好"):"可在設定頁新增預算";const max=top?.[1]||1;$("categoryBars").innerHTML=totals.length?totals.slice(0,6).map(([name,value])=>`<div class="category-bar"><span>${escapeHtml(name)}</span><div class="category-track"><span style="width:${value/max*100}%"></span></div><strong class="private-value">${money.format(value)}</strong></div>`).join(""):emptyState("▥","還沒有分析資料","新增支出後會自動整理分類")}
function renderSavings(){const total=state.legacyWallets.reduce((sum,item)=>sum+item.balance,0);$("legacyTotal").textContent=money.format(total);$("legacyWallets").innerHTML=state.legacyWallets.map(item=>`<article class="legacy-wallet"><span>${escapeHtml(item.label)}</span><strong class="private-value">${money.format(item.balance)}</strong></article>`).join("");$("legacyCount").textContent=`共 ${state.legacyTransactions.length} 筆`;$("legacyTransactions").innerHTML=state.legacyTransactions.length?state.legacyTransactions.slice(0,50).map(item=>transactionRow(item,{legacy:true})).join(""):emptyState("◎","還沒有舊存錢紀錄","原本的資料會在同步後顯示在這裡");renderGoals()}
function renderGoals(){$("goalGrid").innerHTML=state.goals.length?state.goals.map(item=>{const amount=Number(item.amount)||0,saved=Number(item.allocated??item.saved)||0,percent=amount?Math.min(100,saved/amount*100):0;return `<article class="goal-card"><div class="goal-line"><h3>${escapeHtml(item.name)}</h3><small>${percent.toFixed(0)}%</small></div><div class="progress"><span style="width:${percent}%"></span></div><div class="goal-line"><small class="private-value">${money.format(saved)} / ${money.format(amount)}</small><small>${item.targetDate?formatDate(item.targetDate):"慢慢存也很好"}</small></div><footer><small>還差 <b class="private-value">${money.format(Math.max(0,amount-saved))}</b></small><div><button class="mini-button accent" data-goal-add="${item.id}" type="button">放入</button><button class="mini-button" data-goal-edit="${item.id}" type="button">編輯</button></div></footer></article>`}).join(""):emptyState("◎","還沒有存錢目標","新增一個你們想一起完成的計畫")}
function renderGoalPreview(){if(!state.goals.length){$("goalPreview").innerHTML=emptyState("◎","還沒有目標","一起建立第一個存錢計畫");return}const item=state.goals[0],amount=Number(item.amount)||0,saved=Number(item.allocated??item.saved)||0,percent=amount?Math.min(100,saved/amount*100):0;$("goalPreview").innerHTML=`<div class="goal-mini"><div class="goal-line"><strong>${escapeHtml(item.name)}</strong><small>${percent.toFixed(0)}%</small></div><div class="progress"><span style="width:${percent}%"></span></div><small class="private-value">${money.format(saved)} / ${money.format(amount)}</small></div>`}
function renderSettings(){$("accountSettingsList").innerHTML=state.accounts.map(item=>`<div class="settings-account"><div><strong>${escapeHtml(item.name)}</strong><small>${accountTypeLabel(item.type)} · ${escapeHtml(accountOwnerLabel(item))} · <span class="private-value">${money.format(Number(item.balance)||0)}</span></small></div><button class="mini-button" data-account-edit="${item.id}" type="button">編輯</button></div>`).join("");$("memberSettingsList").innerHTML=state.members.map(member=>`<div class="settings-account"><div class="member-info"><span class="member-avatar">${escapeHtml(member.name.slice(0,1))}</span><div><strong>${escapeHtml(member.name)}</strong><small>家庭成員</small></div></div><div class="member-actions">${state.members.length>2?`<button class="mini-button" data-member-delete="${member.id}" type="button">移除</button>`:""}</div></div>`).join("");$("budgetList").innerHTML=state.budgets.length?state.budgets.map(item=>{const spent=categoryTotals().find(([name])=>name===item.category)?.[1]||0,percent=Math.min(100,spent/Number(item.amount)*100);return `<div class="settings-account"><div><strong>${escapeHtml(item.category)}</strong><small class="private-value">${money.format(spent)} / ${money.format(item.amount)} · ${percent.toFixed(0)}%</small></div><button class="mini-button" data-budget-delete="${item.category}" type="button">移除</button></div>`}).join(""):emptyState("%","尚未設定預算","新增分類預算後會自動追蹤");$("privacySwitch").setAttribute("aria-checked",String(state.private));$("themeSwitch").setAttribute("aria-checked",String(state.dark));$("sidebarFamily").textContent=state.familyName;document.body.classList.toggle("dark",state.dark)}
function render(){renderHome();renderSavings();renderSettings();if(state.route==="transactions")renderTransactions();document.body.classList.toggle("private-mode",state.private);$("syncText").textContent=state.cloud?"雲端資料已同步":"目前使用本機資料"}

function openModal(id){$("modalBackdrop").hidden=false;document.querySelectorAll(".sheet").forEach(sheet=>sheet.hidden=sheet.id!==id);document.body.style.overflow="hidden";setTimeout(()=>$(id).querySelector("input:not([type=hidden]),select")?.focus(),80)}
function closeModal(){$("modalBackdrop").hidden=true;document.querySelectorAll(".sheet").forEach(sheet=>sheet.hidden=true);document.body.style.overflow=""}
function settlementAccountOptions(memberId,mode){const accounts=state.accounts.filter(account=>account.ownerId===memberId),label=mode==="from"?"只結清，不扣帳戶":"只結清，不增加帳戶";return accounts.map(account=>`<option value="${account.id}">${escapeHtml(account.name)}（${money.format(Number(account.balance)||0)}）</option>`).join("")+`<option value="">${label}</option>`}
function openSettlement(from,to,amount){const fromMember=memberById(from),toMember=memberById(to),rounded=Math.max(1,Math.round(Number(amount)||0));if(!fromMember||!toMember)return notify("找不到結算成員",true);$("settlementForm").reset();$("settlementFrom").value=from;$("settlementTo").value=to;$("settlementAmount").value=rounded;$("settlementAmount").max=rounded;$("settlementDirection").textContent=`${fromMember.name} 付給 ${toMember.name}`;$("settlementFromAccount").innerHTML=settlementAccountOptions(from,"from");$("settlementToAccount").innerHTML=settlementAccountOptions(to,"to");openModal("settlementModal")}
async function saveSettlement(event){event.preventDefault();const from=$("settlementFrom").value,to=$("settlementTo").value,amount=Number($("settlementAmount").value),current=settlement().find(item=>item.from===from&&item.to===to),maximum=current?Math.max(1,Math.round(current.amount)):0;if(!Number.isSafeInteger(amount)||amount<=0)return notify("請輸入正整數付款金額",true);if(!maximum||amount>maximum)return notify(`目前最多需要結算 ${money.format(maximum)}`,true);const fromAccount=accountById($("settlementFromAccount").value),toAccount=accountById($("settlementToAccount").value);if(fromAccount&&fromAccount.ownerId!==from)return notify("付款帳戶不屬於付款人",true);if(toAccount&&toAccount.ownerId!==to)return notify("收款帳戶不屬於收款人",true);const fromBefore=Number(fromAccount?.balance)||0,toBefore=Number(toAccount?.balance)||0,record={id:`settlement-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,fromMemberId:from,toMemberId:to,amount,fromAccountId:fromAccount?.id||null,toAccountId:toAccount?.id||null,time:new Date().toISOString()};if(fromAccount)fromAccount.balance=fromBefore-amount;if(toAccount)toAccount.balance=toBefore+amount;state.settlements.unshift(record);saveLocalLedger();render();closeModal();notify("已記錄付款，分攤餘額已更新");if(db&&state.cloud)try{await db.runTransaction(async transaction=>{const fromRef=fromAccount?db.collection("ledgerAccounts").doc(fromAccount.id):null,toRef=toAccount?db.collection("ledgerAccounts").doc(toAccount.id):null,settlementRef=db.collection("ledgerSettlements").doc(record.id),docs=await Promise.all([fromRef?transaction.get(fromRef):null,toRef?transaction.get(toRef):null]);if(fromRef){const stored=docs[0]?.exists?Number(docs[0].data().balance)||0:fromBefore;transaction.set(fromRef,{...fromAccount,balance:stored-amount,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}if(toRef){const stored=docs[1]?.exists?Number(docs[1].data().balance)||0:toBefore;transaction.set(toRef,{...toAccount,balance:stored+amount,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}transaction.set(settlementRef,{...record,time:firebase.firestore.Timestamp.fromDate(toDate(record.time))})})}catch(error){console.warn("結算無法同步，已保留本機紀錄",error);state.cloud=false;render()}}
async function undoSettlement(id){const record=state.settlements.find(item=>item.id===id);if(!record||!confirm(`確定撤銷這筆 ${money.format(record.amount)} 的結算嗎？`))return;const fromAccount=accountById(record.fromAccountId),toAccount=accountById(record.toAccountId),fromBefore=Number(fromAccount?.balance)||0,toBefore=Number(toAccount?.balance)||0;if(fromAccount)fromAccount.balance=fromBefore+Number(record.amount);if(toAccount)toAccount.balance=toBefore-Number(record.amount);state.settlements=state.settlements.filter(item=>item.id!==id);saveLocalLedger();render();notify("結算已撤銷，帳戶餘額已回復");if(db&&state.cloud)try{await db.runTransaction(async transaction=>{const fromRef=fromAccount?db.collection("ledgerAccounts").doc(fromAccount.id):null,toRef=toAccount?db.collection("ledgerAccounts").doc(toAccount.id):null,settlementRef=db.collection("ledgerSettlements").doc(record.id),docs=await Promise.all([fromRef?transaction.get(fromRef):null,toRef?transaction.get(toRef):null]);if(fromRef){const stored=docs[0]?.exists?Number(docs[0].data().balance)||0:fromBefore;transaction.set(fromRef,{...fromAccount,balance:stored+Number(record.amount),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}if(toRef){const stored=docs[1]?.exists?Number(docs[1].data().balance)||0:toBefore;transaction.set(toRef,{...toAccount,balance:stored-Number(record.amount),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}transaction.delete(settlementRef)})}catch(error){console.warn("撤銷結算無法同步，已保留本機結果",error);state.cloud=false;render()}}
function setEntryKind(kind){state.entryKind=kind;document.querySelectorAll("[data-kind]").forEach(button=>button.classList.toggle("active",button.dataset.kind===kind));$("saveTransactionButton").textContent=kind==="income"?"儲存收入":"儲存支出";$("entryCategory").innerHTML=(kind==="income"?incomeCategories:expenseCategories).map(item=>`<option>${item}</option>`).join("");updateEntryScope()}
function updateSplitSummary(){const values=[...document.querySelectorAll(".split-allocation")].reduce((sum,input)=>sum+Number(input.value||0),0),type=$("entrySplit").value,target=type==="percent"?100:Number($("entryAmount").value||0),unit=type==="percent"?"%":" 元",summary=document.querySelector(".split-summary");if(summary){summary.textContent=`目前合計 ${values.toFixed(type==="percent"?1:0)}${unit}／應為 ${target.toFixed(type==="percent"?0:0)}${unit}`;summary.style.color=Math.abs(values-target)<.01?"var(--green)":"var(--red)"}}
function handleAllocationInput(event){const type=$("entrySplit").value;if(!["percent","amount"].includes(type))return updateSplitSummary();const active=event.target,inputs=[...document.querySelectorAll(".split-allocation")],others=inputs.filter(input=>input!==active),target=type==="percent"?100:Number($("entryAmount").value||0),raw=Number(active.value||0),value=Math.max(0,Math.min(target,type==="amount"?Math.round(raw):Math.round(raw*100)/100));if(raw!==value)active.value=value;if(!others.length)return updateSplitSummary();const remaining=target-value,previousTotal=others.reduce((sum,input)=>sum+Number(input.value||0),0);let used=0;others.forEach((input,index)=>{let next;if(index===others.length-1)next=remaining-used;else{const proportional=previousTotal>0?remaining*Number(input.value||0)/previousTotal:remaining/others.length;next=type==="amount"?Math.round(proportional):Math.round(proportional*100)/100;next=Math.max(0,Math.min(remaining-used,next))}used+=next;input.value=next});updateSplitSummary()}
function handleEntryAmountInput(){const inputs=[...document.querySelectorAll(".split-allocation")];if($("entrySplit").value==="amount"&&inputs.length)return handleAllocationInput({target:inputs[0]});updateSplitSummary()}
function renderSplitDetails(existing=[]){const type=$("entrySplit").value,personalAccount=accountById($("entryAccount").value)?.ownerId!=="shared",show=state.entryKind==="expense"&&personalAccount&&["percent","amount"].includes(type);$("splitDetails").hidden=!show;if(!show){$("splitDetails").innerHTML="";return}const total=type==="percent"?100:Number($("entryAmount").value||0),count=Math.max(1,state.members.length);let used=0;$("splitDetails").innerHTML=`<div class="split-title"><strong>${type==="percent"?"設定每位成員比例":"設定每位成員金額"}</strong><small>${type==="percent"?"調整一人，其他人會自動補足 100%":"調整一人，其他人會用整數自動補足總額"}</small></div>${state.members.map((member,index)=>{const saved=existing.find(entry=>entry.memberId===member.id),defaultValue=type==="amount"?Math.floor(total/count):Math.floor(total/count*100)/100,value=saved?Number(saved.value):index===count-1?total-used:defaultValue;used+=value;return `<div class="split-member-row"><label><span class="member-avatar">${escapeHtml(member.name.slice(0,1))}</span>${escapeHtml(member.name)}</label><div class="split-input-wrap"><input class="split-allocation" data-member-id="${member.id}" type="number" min="0" ${type==="percent"?'max="100" step="0.01"':'step="1" inputmode="numeric"'} value="${value}"><span>${type==="percent"?"%":"元"}</span></div></div>`}).join("")}<div class="split-summary"></div>`;document.querySelectorAll(".split-allocation").forEach(input=>input.addEventListener("input",handleAllocationInput));updateSplitSummary()}
function readAllocations(){const integer=$("entrySplit").value==="amount";return [...document.querySelectorAll(".split-allocation")].map(input=>({memberId:input.dataset.memberId,value:integer?Math.round(Number(input.value||0)):Number(input.value||0)}))}
function updateEntryScope(allocations=[],preferredPayer=null){if(!Array.isArray(allocations))allocations=[];const account=accountById($("entryAccount").value),sharedAccount=account?.ownerId==="shared",expense=state.entryKind==="expense",ownerName=accountOwnerLabel(account),currentPayer=preferredPayer||$("entryPaidBy").value||account?.ownerId||state.members[0]?.id;$("payerField").hidden=!expense;$("splitField").hidden=!expense||sharedAccount;if(sharedAccount){$("entrySplit").value="none";$("entryPaidBy").innerHTML='<option value="shared">共同帳戶</option>';$("entryPaidBy").disabled=true}else{$("entryPaidBy").innerHTML=state.members.map(member=>`<option value="${member.id}">${escapeHtml(member.name)}</option>`).join("");$("entryPaidBy").value=state.members.some(member=>member.id===currentPayer)?currentPayer:account?.ownerId||state.members[0]?.id;$("entryPaidBy").disabled=false}$("accountOwnerHint").textContent=sharedAccount?"這是一起存的共同帳戶，由共同資金付款，不需要再分攤。":`這是 ${ownerName} 的個人帳戶。付款人預設為帳戶擁有人，也可以改選實際代墊的家庭成員。`;renderSplitDetails(allocations)}
function openTransaction(item=null){if(!state.accounts.length)return notify("請先新增一個帳戶",true);$("transactionForm").reset();$("transactionEditId").value=item?.id||"";$("entryAccount").innerHTML=state.accounts.map(account=>`<option value="${account.id}">${escapeHtml(account.name)}（${escapeHtml(accountOwnerLabel(account))}）</option>`).join("");setEntryKind(item?transactionKind(item):"expense");$("entryAmount").value=item?.amount||"";$("entryAccount").value=item?.accountId||state.accounts[0].id;$("entryCategory").value=item?.category||$("entryCategory").value;$("entryDate").value=item?toDate(item.time).toLocaleDateString("en-CA"):new Date().toLocaleDateString("en-CA");$("entrySplit").value=item?.split||"none";$("entryNote").value=item?.note||"";$("entryRecurring").checked=Boolean(item?.recurring);$("transactionModalTitle").textContent=item?"編輯這筆記帳":"新增一筆記帳";$("deleteTransactionButton").hidden=!item;updateEntryScope(item?.allocations||[],item?.paidBy);openModal("transactionModal")}
async function persistTransaction(item,account){const delta=item.kind==="income"?item.amount:-item.amount,previous=account.balance;account.balance=Number(account.balance||0)+delta;state.transactions.unshift(item);saveLocalLedger();render();if(db&&state.cloud){try{await db.runTransaction(async transaction=>{const accountRef=db.collection("ledgerAccounts").doc(account.id),itemRef=db.collection("ledgerTransactions").doc(item.id),accountDoc=await transaction.get(accountRef),stored=accountDoc.exists?Number(accountDoc.data().balance)||0:previous;transaction.set(accountRef,{...account,balance:stored+delta,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});transaction.set(itemRef,{...item,time:firebase.firestore.Timestamp.fromDate(toDate(item.time))})})}catch(error){console.warn("雲端記帳失敗，保留本機資料",error);state.cloud=false}}}
async function updateExistingTransaction(existing,next){const oldAccount=accountById(existing.accountId),newAccount=accountById(next.accountId),oldDelta=transactionKind(existing)==="income"?Number(existing.amount):-Number(existing.amount),newDelta=next.kind==="income"?next.amount:-next.amount;if(!oldAccount||!newAccount)return notify("找不到原本帳戶",true);const oldBefore=oldAccount.balance,newBefore=newAccount.balance;if(oldAccount.id===newAccount.id)oldAccount.balance=Number(oldAccount.balance)-oldDelta+newDelta;else{oldAccount.balance=Number(oldAccount.balance)-oldDelta;newAccount.balance=Number(newAccount.balance)+newDelta}Object.assign(existing,next,{id:existing.id});saveLocalLedger();render();if(db&&state.cloud)try{await db.runTransaction(async transaction=>{const oldRef=db.collection("ledgerAccounts").doc(oldAccount.id),newRef=db.collection("ledgerAccounts").doc(newAccount.id),itemRef=db.collection("ledgerTransactions").doc(existing.id),oldDoc=await transaction.get(oldRef),oldStored=oldDoc.exists?Number(oldDoc.data().balance)||0:oldBefore;if(oldAccount.id===newAccount.id)transaction.set(oldRef,{...oldAccount,balance:oldStored-oldDelta+newDelta,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});else{const newDoc=await transaction.get(newRef),newStored=newDoc.exists?Number(newDoc.data().balance)||0:newBefore;transaction.set(oldRef,{...oldAccount,balance:oldStored-oldDelta,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});transaction.set(newRef,{...newAccount,balance:newStored+newDelta,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}transaction.set(itemRef,{...existing,time:firebase.firestore.Timestamp.fromDate(toDate(existing.time))})})}catch(error){console.warn("雲端修改失敗，保留本機結果",error);state.cloud=false}}
async function saveTransaction(event){event.preventDefault();const amount=Number($("entryAmount").value),account=accountById($("entryAccount").value),editId=$("transactionEditId").value,existing=state.transactions.find(item=>item.id===editId),sharedAccount=account?.ownerId==="shared",split=sharedAccount||state.entryKind!=="expense"?"none":$("entrySplit").value,scope=sharedAccount?"shared":split==="none"?"personal":"shared",paidBy=sharedAccount?"shared":$("entryPaidBy").value,allocations=["percent","amount"].includes(split)?readAllocations():[];if(!Number.isSafeInteger(amount)||amount<=0)return notify("請輸入有效金額",true);if(!account)return notify("請選擇帳戶",true);if(!sharedAccount&&!state.members.some(member=>member.id===paidBy))return notify("請選擇實際付款人",true);if(allocations.some(entry=>!Number.isFinite(entry.value)||entry.value<0))return notify("每位成員的分攤必須是有效數字",true);if(allocations.length){const total=allocations.reduce((sum,entry)=>sum+entry.value,0),target=split==="percent"?100:amount;if(Math.abs(total-target)>.01)return notify(split==="percent"?"分攤百分比合計必須等於 100%":"自訂分攤金額合計必須等於交易金額",true)}const item={id:existing?.id||`txn-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,kind:state.entryKind,accountId:account.id,amount,category:$("entryCategory").value,date:$("entryDate").value,note:$("entryNote").value.trim(),scope,fund:sharedAccount?"shared":"personal",paidBy,split,allocations,recurring:$("entryRecurring").checked,time:new Date(`${$("entryDate").value}T12:00:00`).toISOString()};existing?await updateExistingTransaction(existing,item):await persistTransaction(item,account);closeModal();notify(existing?"這筆記帳已更新":`${state.entryKind==="income"?"收入":"支出"}已記錄${item.recurring?"，並設為每月固定":""}`)}
async function deleteCurrentTransaction(){const id=$("transactionEditId").value,item=state.transactions.find(record=>record.id===id);if(!item||!confirm("確定刪除這筆記帳嗎？帳戶餘額會自動回沖。"))return;const account=accountById(item.accountId),delta=transactionKind(item)==="income"?Number(item.amount):-Number(item.amount),before=account?.balance||0;if(account)account.balance=Number(account.balance)-delta;state.transactions=state.transactions.filter(record=>record.id!==id);saveLocalLedger();render();closeModal();notify("記帳已刪除，餘額已回沖");if(db&&state.cloud&&account)try{await db.runTransaction(async transaction=>{const accountRef=db.collection("ledgerAccounts").doc(account.id),itemRef=db.collection("ledgerTransactions").doc(id),doc=await transaction.get(accountRef),stored=doc.exists?Number(doc.data().balance)||0:before;transaction.set(accountRef,{...account,balance:stored-delta,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});transaction.delete(itemRef)})}catch(error){console.warn("雲端刪除失敗，保留本機結果",error);state.cloud=false}}
function openAccount(item=null){$("accountForm").reset();$("accountOwner").innerHTML='<option value="shared">共同帳戶（一起存的錢）</option>'+state.members.map(member=>`<option value="${member.id}">${escapeHtml(member.name)}的個人帳戶</option>`).join("");$("accountEditId").value=item?.id||"";$("accountName").value=item?.name||"";$("accountType").value=item?.type||"cash";$("accountOwner").value=item?.ownerId||"shared";$("accountBalance").value=Number(item?.balance)||0;$("accountModalTitle").textContent=item?"編輯帳戶":"新增帳戶";openModal("accountModal")}
async function saveAccount(event){event.preventDefault();const editId=$("accountEditId").value,name=$("accountName").value.trim(),existing=accountById(editId),item={id:editId||`account-${Date.now()}`,name,type:$("accountType").value,ownerId:$("accountOwner").value,balance:Number($("accountBalance").value)||0};if(!name)return;existing?Object.assign(existing,item):state.accounts.push(item);saveLocalLedger();render();closeModal();notify(existing?"帳戶已更新":"帳戶已新增");if(db&&state.cloud)try{await db.collection("ledgerAccounts").doc(item.id).set(item,{merge:true})}catch(error){console.warn(error)}}
function openGoal(item=null){$("goalForm").reset();$("goalEditId").value=item?.id||"";$("goalName").value=item?.name||"";$("goalAmount").value=Number(item?.amount)||"";$("goalSaved").value=Number(item?.allocated??item?.saved)||0;$("goalDate").value=item?.targetDate||"";$("goalModalTitle").textContent=item?"編輯存錢目標":"新增存錢目標";openModal("goalModal")}
async function persistGoals(message){saveLocalGoals();render();if(db&&state.cloud)try{await db.collection("settings").doc("savingsGoals").set({items:state.goals,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(error){console.warn(error);state.cloud=false}notify(message)}
async function saveGoal(event){event.preventDefault();const id=$("goalEditId").value,existing=state.goals.find(item=>item.id===id),amount=Number($("goalAmount").value),allocated=Number($("goalSaved").value);if(amount<=0||allocated<0||allocated>amount)return notify("請確認目標與已存金額",true);const item={id:id||`goal-${Date.now()}`,name:$("goalName").value.trim(),amount,allocated,targetDate:$("goalDate").value,walletId:"all"};existing?Object.assign(existing,item):state.goals.push(item);closeModal();await persistGoals(existing?"目標已更新":"目標已建立")}
async function addToGoal(id){const item=state.goals.find(goal=>goal.id===id),remaining=Number(item.amount)-Number(item.allocated||0);if(!item||remaining<=0)return notify("這個目標已經完成");const input=prompt(`要放入「${item.name}」多少錢？\n這只調整存錢目標，不會計入記帳支出。`,String(Math.min(1000,remaining)));if(input===null)return;const amount=Number(input);if(!Number.isSafeInteger(amount)||amount<=0||amount>remaining)return notify("請輸入有效且不超過剩餘目標的金額",true);item.allocated=Number(item.allocated||0)+amount;await persistGoals(`已放入 ${money.format(amount)}`)}
function togglePrivacy(){state.private=!state.private;localStorage.setItem("moneycanPrivate",state.private?"1":"0");render();$("privacyButton").textContent=state.private?"◌":"◉"}
function toggleTheme(){state.dark=!state.dark;localStorage.setItem("moneycanDark",state.dark?"1":"0");render()}
async function saveBudget(event){event.preventDefault();const category=$("budgetCategory").value,amount=Number($("budgetAmount").value);if(!Number.isSafeInteger(amount)||amount<=0)return notify("請輸入有效預算",true);const existing=state.budgets.find(item=>item.category===category);existing?existing.amount=amount:state.budgets.push({category,amount});$("budgetAmount").value="";await persistMembers();notify("預算已儲存")}
async function deleteBudget(category){state.budgets=state.budgets.filter(item=>item.category!==category);await persistMembers();notify("預算已移除")}
async function materializeRecurring(){const now=new Date(),month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`,templates=state.transactions.filter(item=>item.recurring&&!item.recurringParent);for(const template of templates){const original=toDate(template.time),originalMonth=`${original.getFullYear()}-${String(original.getMonth()+1).padStart(2,"0")}`;if(originalMonth===month||state.transactions.some(item=>item.recurringParent===template.id&&item.occurrenceMonth===month))continue;const day=Math.min(original.getDate(),new Date(now.getFullYear(),now.getMonth()+1,0).getDate()),time=new Date(now.getFullYear(),now.getMonth(),day,12),account=accountById(template.accountId);if(!account)continue;await persistTransaction({...template,id:`recurring-${template.id}-${month}`,time:time.toISOString(),date:time.toLocaleDateString("en-CA"),recurring:false,recurringParent:template.id,occurrenceMonth:month},account);notify("已建立本月固定帳目")}}
async function persistMembers(){saveLocalLedger();render();if(db&&state.cloud)try{await db.collection("settings").doc("household").set({name:state.familyName,members:state.members,budgets:state.budgets,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(error){console.warn(error)}}
async function addMember(){const name=prompt("新成員名稱（例如：媽媽、哥哥）");if(!name?.trim())return;if(state.members.length>=8)return notify("目前最多 8 位家庭成員",true);state.members.push({id:`member-${Date.now()}`,name:name.trim()});await persistMembers();notify("家庭成員已新增")}
async function removeMember(id){const member=memberById(id);if(!member||!confirm(`確定移除「${member.name}」嗎？舊交易仍會保留名字。`))return;state.members=state.members.filter(item=>item.id!==id);await persistMembers();notify("家庭成員已移除")}
function exportData(){const payload={exportedAt:new Date().toISOString(),familyName:state.familyName,members:state.members,budgets:state.budgets,accounts:state.accounts,transactions:state.transactions,settlements:state.settlements,legacyWallets:state.legacyWallets,legacyTransactions:state.legacyTransactions,goals:state.goals},blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`moneycan-backup-${new Date().toLocaleDateString("en-CA")}.json`;link.click();URL.revokeObjectURL(url);notify("備份已下載")}
function exportCsv(){const quote=value=>`"${String(value??"").replaceAll('"','""')}"`,rows=[["日期","類型","帳戶","分類","金額","帳本","付款人","備註"],...state.transactions.map(item=>[toDate(item.time).toLocaleDateString("en-CA"),transactionKind(item)==="income"?"收入":"支出",accountById(item.accountId)?.name||"",item.category,item.amount,item.scope==="personal"?"個人":"共同",memberById(item.paidBy)?.name||"",item.note||""])],blob=new Blob(["\ufeff"+rows.map(row=>row.map(quote).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`moneycan-transactions-${new Date().toLocaleDateString("en-CA")}.csv`;link.click();URL.revokeObjectURL(url);notify("CSV 明細已下載")}
async function importBackup(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.accounts)||!Array.isArray(data.transactions))throw new Error("格式不正確");if(!confirm(`將匯入 ${data.transactions.length} 筆記帳資料並覆蓋目前本機帳本，確定嗎？`))return;state.accounts=data.accounts;state.transactions=data.transactions;state.settlements=Array.isArray(data.settlements)?data.settlements:[];state.members=Array.isArray(data.members)&&data.members.length?data.members:state.members;state.budgets=Array.isArray(data.budgets)?data.budgets:state.budgets;state.familyName=data.familyName||state.familyName;saveLocalLedger();localStorage.setItem("moneycanFamilyName",state.familyName);state.cloud=false;render();notify("備份已還原")}catch(error){notify("無法讀取這份備份",true)}}

document.addEventListener("click",event=>{const route=event.target.closest("[data-route]")?.dataset.route;if(route)return setRoute(route);if(event.target.closest("[data-close-modal]"))return closeModal();const settlementPay=event.target.closest("[data-settlement-pay]");if(settlementPay)return openSettlement(settlementPay.dataset.from,settlementPay.dataset.to,Number(settlementPay.dataset.amount));const settlementUndo=event.target.closest("[data-settlement-undo]")?.dataset.settlementUndo;if(settlementUndo)return undoSettlement(settlementUndo);const transactionEdit=event.target.closest("[data-transaction-edit]")?.dataset.transactionEdit;if(transactionEdit)return openTransaction(state.transactions.find(item=>item.id===transactionEdit));const accountEdit=event.target.closest("[data-account-edit]")?.dataset.accountEdit;if(accountEdit)return openAccount(accountById(accountEdit));const goalEdit=event.target.closest("[data-goal-edit]")?.dataset.goalEdit;if(goalEdit)return openGoal(state.goals.find(item=>item.id===goalEdit));const goalAdd=event.target.closest("[data-goal-add]")?.dataset.goalAdd;if(goalAdd)return addToGoal(goalAdd);const memberDelete=event.target.closest("[data-member-delete]")?.dataset.memberDelete;if(memberDelete)return removeMember(memberDelete);const budgetDelete=event.target.closest("[data-budget-delete]")?.dataset.budgetDelete;if(budgetDelete)return deleteBudget(budgetDelete)});
$("modalBackdrop").addEventListener("click",event=>{if(event.target===$("modalBackdrop"))closeModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal()});
[$("quickAddTop"),$("mobileAddButton"),$("addTransactionButton")].forEach(button=>button.addEventListener("click",()=>openTransaction()));[$("addAccountButton"),$("addAccountSettings")].forEach(button=>button.addEventListener("click",()=>openAccount()));$("addGoalButton").addEventListener("click",()=>openGoal());$("addMemberButton").addEventListener("click",addMember);$("deleteTransactionButton").addEventListener("click",deleteCurrentTransaction);$("transactionForm").addEventListener("submit",saveTransaction);$("accountForm").addEventListener("submit",saveAccount);$("goalForm").addEventListener("submit",saveGoal);$("budgetForm").addEventListener("submit",saveBudget);document.querySelectorAll("[data-kind]").forEach(button=>button.addEventListener("click",()=>setEntryKind(button.dataset.kind)));$("entryScope").addEventListener("change",updateEntryScope);[$("privacyButton"),$("privacySwitch")].forEach(button=>button.addEventListener("click",togglePrivacy));$("themeSwitch").addEventListener("click",toggleTheme);$("editFamilyButton").addEventListener("click",async()=>{const value=prompt("家庭帳本名稱",state.familyName);if(value?.trim()){state.familyName=value.trim();localStorage.setItem("moneycanFamilyName",state.familyName);await persistMembers()}});$("exportButton").addEventListener("click",exportData);$("csvButton").addEventListener("click",exportCsv);$("importButton").addEventListener("click",()=>$("importFile").click());$("importFile").addEventListener("change",event=>{if(event.target.files[0])importBackup(event.target.files[0]);event.target.value=""});$("installButton").addEventListener("click",async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$("installButton").hidden=true});[$("transactionSearch"),$("transactionType"),$("transactionAccount"),$("transactionMonth")].forEach(input=>input.addEventListener(input.tagName==="INPUT"?"input":"change",renderTransactions));
$("settlementForm").addEventListener("submit",saveSettlement);
$("entrySplit").addEventListener("change",()=>renderSplitDetails());$("entryAmount").addEventListener("input",handleEntryAmountInput);
$("entryAccount").addEventListener("change",()=>{const account=accountById($("entryAccount").value);updateEntryScope([],account?.ownerId)});

async function init(){const now=new Date();$("todayText").textContent=now.toLocaleDateString("zh-TW",{year:"numeric",month:"long",day:"numeric",weekday:"short"});await Promise.all([loadLedger(),loadLegacy()]);await materializeRecurring();$("transactionAccount").innerHTML='<option value="all">全部帳戶</option>'+state.accounts.map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join("");$("budgetCategory").innerHTML=expenseCategories.map(item=>`<option>${item}</option>`).join("");$("transactionMonth").value=now.toLocaleDateString("en-CA").slice(0,7);state.route=location.hash.slice(1)||"home";if(!["home","transactions","savings","settings"].includes(state.route))state.route="home";$("privacyButton").textContent=state.private?"◌":"◉";setRoute(state.route);render();if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(error=>console.warn("離線服務註冊失敗",error))}
window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();state.installPrompt=event;$("installButton").hidden=false});
init().catch(error=>{console.error(error);notify("資料載入失敗，請重新整理",true)});
